// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-6IGqiJDHAsKzvhdfiiNyIyBMW0AVBXI',
    appId: '1:538292676078:web:e798a4d5f644a6163e5aff',
    messagingSenderId: '538292676078',
    projectId: 'stex-46216',
    authDomain: 'stex-46216.firebaseapp.com',
    databaseURL: 'https://stex-46216-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stex-46216.firebasestorage.app',
    measurementId: 'G-RFVLZ91RCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS-JtMN_aZPAydlr6ZBL-_1bq5h9SLfOk',
    appId: '1:538292676078:android:ae4a9b2e4cb717be3e5aff',
    messagingSenderId: '538292676078',
    projectId: 'stex-46216',
    databaseURL: 'https://stex-46216-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stex-46216.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAazusJxV2Tv_lJKgOmnWL1nlUJx9Z1Obs',
    appId: '1:538292676078:ios:d27f54f8b2a9765e3e5aff',
    messagingSenderId: '538292676078',
    projectId: 'stex-46216',
    databaseURL: 'https://stex-46216-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stex-46216.firebasestorage.app',
    iosBundleId: 'com.example.touristApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAazusJxV2Tv_lJKgOmnWL1nlUJx9Z1Obs',
    appId: '1:538292676078:ios:d27f54f8b2a9765e3e5aff',
    messagingSenderId: '538292676078',
    projectId: 'stex-46216',
    databaseURL: 'https://stex-46216-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stex-46216.firebasestorage.app',
    iosBundleId: 'com.example.touristApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-6IGqiJDHAsKzvhdfiiNyIyBMW0AVBXI',
    appId: '1:538292676078:web:ad72a1fbe002d4743e5aff',
    messagingSenderId: '538292676078',
    projectId: 'stex-46216',
    authDomain: 'stex-46216.firebaseapp.com',
    databaseURL: 'https://stex-46216-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stex-46216.firebasestorage.app',
    measurementId: 'G-756B9Y1R9J',
  );

}